services:
  rocketchat:
    build:
      context: .
    environment:
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASS: ${ADMIN_PASS}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_NAME: ${ADMIN_NAME}
      ROOT_URL: http://localhost:3000
      PORT: 3000
      MONGO_URL: mongodb://mongodb:27017/rocketchat?replicaSet=rs0
      MONGO_OPLOG_URL: mongodb://mongodb:27017/local?replicaSet=rs0
      OVERWRITE_SETTING_Show_Setup_Wizard: completed
    network_mode: service:mongodb
    depends_on:
      - mongodb
    volumes:
      - ../../:/workspaces:cached

  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    volumes:
      - ../../data:/bitnami/mongodb:cached
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: "true"
      ALLOW_EMPTY_PASSWORD: "yes"